name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
	# 只有在master分支发生push时间时，触发本workflow
jobs:
  update_release_draft:
    # 指定虚拟机环境，必填字段
    runs-on: ubuntu-latest
    steps:
      # 指定每个job的运行步骤，包含一个或多少步骤
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        with:
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          # config-name: my-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
