name: Release
on: push

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
    # Checks out a copy of your repository on the ubuntu-latest machine
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
	python-version: '3.7'

    - name: Display Python version
      run: python -c "import sys; print(sys.version)" 
    
    - name: Install dependencies
      run: npm ci

    - name: Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
